default_config:

http:
  use_x_forwarded_for: true
  trusted_proxies: !secret http_trusted_proxies

# mariadb database (add-on)
recorder:
  purge_keep_days: 5
  include:
    domains:
      - sensor
      - light
      - climate
      - person
    entities:
      # Zon
      - sun.sun
      # Accounts of personen
      # Telefoon
      - device_tracker.iphone_12_van_maarten
      # Binaire sensoren
      - binary_sensor.slave_diagnostic_indication_boiler_otgw
      - binary_sensor.central_heating_activity

logbook:
  include:
    domains:
      - sensor
      - light
      - climate
      - person
    entities:
      # Zon
      - sun.sun
      # Accounts of personen
      # Telefoon
      - device_tracker.iphone_12_van_maarten
  exclude:
    entities:
      - sensor.dsmr_reading_timestamp
      - sensor.time
      - sensor.dsmr_consumption_gas_read_at
      - sensor.thuis_pressure_tendency

logger:
  default: warning
  logs:
    pychromecast.socket_client: critical # Mute cast reconnection warnings/errors

# Uitgebreide onderdelen
automation: !include_dir_merge_list automations/
script: !include_dir_merge_named scripts/
zone: !include_dir_merge_list zones/
sensor: !include_dir_merge_list sensors/
input_boolean: !include input/boolean.yaml
input_button: !include input/button.yaml
input_datetime: !include input/datetime.yaml
input_number: !include input/number.yaml
input_select: !include input/select.yaml
notify: !include notify.yaml
timer: !include timer.yaml
template: !include templates.yaml
mqtt: !include mqtt.yaml
rest: !include rest.yaml

zha:
  zigpy_config:
    ota:
      z2m_remote_index: https://raw.githubusercontent.com/Koenkk/zigbee-OTA/master/index.json
