# Check GitHub repository dsmrreader/dsmr-reader via https://api.github.com/repos/dsmrreader/dsmr-reader/releases
- platform: rest
  unique_id: 06df5ab3-70e8-48b2-b83c-da5acc620624
  scan_interval: 3600
  resource: https://api.github.com/repos/dsmrreader/dsmr-reader/releases
  name: "DSMR Reader"
  icon: mdi:gauge
  value_template: "{{ value_json.0.tag_name }}"
  json_attributes:
    - prerelease
    - html_url
  username: !secret github_username
  password: !secret github_personal_access_token
  authentication: basic
  headers:
    accept: application/vnd.github.v3+json
    content-type: application/json
    user-agent: &ua_string "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/116.0"

# Check GitHub repository xirixiz/homeassistant-afvalwijzer via https://api.github.com/repos/xirixiz/homeassistant-afvalwijzer/releases
- platform: rest
  unique_id: 0ecd889e-2679-44d1-ac34-30531c35ddcb
  scan_interval: 3600
  resource: https://api.github.com/repos/xirixiz/homeassistant-afvalwijzer/releases
  name: "Afvalwijzer"
  icon: mdi:delete-restore
  value_template: "{{ value_json.0.tag_name }}"
  json_attributes:
    - prerelease
    - html_url
  username: !secret github_username
  password: !secret github_personal_access_token
  authentication: basic
  headers:
    accept: application/vnd.github.v3+json
    content-type: application/json
    user-agent: *ua_string

# Check GitHub repository nextcloud/server via https://api.github.com/repos/nextcloud/server/releases
- platform: rest
  unique_id: a8c86d93-b746-44f9-88d6-03901cfc5319
  scan_interval: 3600
  resource: https://api.github.com/repos/nextcloud/server/releases
  name: "Nextcloud"
  icon: mdi:folder-sync
  value_template: "{{ value_json.0.tag_name }}"
  json_attributes:
    - prerelease
    - html_url
  username: !secret github_username
  password: !secret github_personal_access_token
  authentication: basic
  headers:
    accept: application/vnd.github.v3+json
    content-type: application/json
    user-agent: *ua_string

# Check GitHub repository kalkih/mini-graph-card via https://api.github.com/repos/kalkih/mini-graph-card/releases
- platform: rest
  unique_id: 8ad8b831-6662-40e9-abb3-e5bae0f8da52
  scan_interval: 3600
  resource: https://api.github.com/repos/kalkih/mini-graph-card/releases
  name: "Mini Graph"
  icon: mdi:chart-line-variant
  value_template: "{{ value_json.0.tag_name }}"
  json_attributes:
    - prerelease
    - html_url
  username: !secret github_username
  password: !secret github_personal_access_token
  authentication: basic
  headers:
    accept: application/vnd.github.v3+json
    content-type: application/json
    user-agent: *ua_string

# Check GitHub repository caddyserver/caddy via https://api.github.com/repos/caddyserver/caddy/releases
- platform: rest
  unique_id: 9d3effaf-f8b5-4e97-a57f-59c93503d936
  scan_interval: 3600
  resource: https://api.github.com/repos/caddyserver/caddy/releases
  name: "Caddy"
  icon: mdi:web-box
  value_template: "{{ value_json.0.tag_name }}"
  json_attributes:
    - prerelease
    - html_url
  username: !secret github_username
  password: !secret github_personal_access_token
  authentication: basic
  headers:
    accept: application/vnd.github.v3+json
    content-type: application/json
    user-agent: *ua_string

# Check GitHub repository Koenkk/Z-Stack-firmware via https://api.github.com/repos/Koenkk/Z-Stack-firmware/releases
- platform: rest
  unique_id: 8a6fafe0-f14a-4dd9-9a80-71396b9e522e
  scan_interval: 3600
  resource: https://api.github.com/repos/Koenkk/Z-Stack-firmware/releases
  name: "Z-Stack firmware releases"
  value_template: "{{ value_json | map(attribute='tag_name') | select('contains', 'coordinator') | first }}"
  json_attributes:
    - prerelease
    - html_url
  username: !secret github_username
  password: !secret github_personal_access_token
  authentication: basic
  headers:
    accept: application/vnd.github.v3+json
    content-type: application/json
    user-agent: *ua_string

- platform: rest
  unique_id: 916cb168-f289-4363-9ad3-d28e70f5a4e3
  scan_interval: 86400
  resource: https://www.virten.net/repo/esxiReleases.json
  name: "ESXi Patch"
  icon: mdi:bandage
  value_template: >-
    {% set releases = value_json.data.esxiReleases[:8] | map(attribute='friendlyName') | list -%}
    {%- for release in releases -%}
        {%- set version = release.split()[1] | regex_findall_index('\\d+\\.\\d+', index=0) -%}
        {# Change version numbers below if necessary for new major releases. Version numbers like 10.0 and higher are supported. #}
        {%- if 9.0 > float(version) >= 8.0 -%}
            {{- release.split('ESXi ') | last -}}
            {% break %}
        {%- endif -%}
    {%- endfor -%}
  headers:
    content-type: application/json
    user-agent: *ua_string
